# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc0803c09cd62076a1986a77bcd39447fb23b56b7daa3212c100f28c4f7772f73c973d78eef72135f1d57a5498f191694ef55284bb2e848ec1cee1530122b6df

test:
  secret_key_base: 80330fa60c87e8168b437deecb641d6adb1a26a096af45c35485341710789be9020d840478490ff77b933321beacc5e3ef6adf378043d72dd7c48811c54914a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
